name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set Select Option Field
        id: set-select-option-id
        uses: ./
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          project-number: 1
          project-owner: infinite-automations
          field-name: Test select field
          select-option-name: Option2
          item-id: PVTI_lADOCOJGKs4AX9CyzgOVcds
